Key_Inventory_application/keyInventory/keyInventory/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.conf import settings
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.staticfiles.urls import static



urlpatterns = [
    url('keys/', include("keys.urls")),
    url('admin/', admin.site.urls),
    url('accounts/',  include('django.contrib.auth.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#path form the keys application

Key_Inventory_application/keyInventory/keys/models.py
from django.db import models

class building(models.Model):
    identifier = models.CharField(max_length=255, unique=True)
    name = models.CharField(max_length=100, null=False)
    code = models.CharField(max_length=6, null=False)
    is_residential = models.BooleanField(null=False)
    is_inactive = models.BooleanField(null=False)
    version = models.IntegerField(null=True)

    def _str_(self):
        return self.identifier

class keytype(models.Model):
    identifier = models.CharField(max_length=255, unique=True)
    code = models.CharField(max_length=255, null=False)
    manu_info = models.CharField(max_length=255, null=False)
    description = models.CharField(max_length=255, null=True)
    building_id = models.ForeignKey(building, on_delete=models.SET_NULL, blank=True, null=True)
    def _str_(self):
        return self.identifier

#class keytypes
class key(models.Model):
    identifier = models.CharField(max_length=255, unique=True)
    number = models.IntegerField(null=False)
    keytype_id = models.ForeignKey(keytype,  on_delete=models.CASCADE, blank= False, null=False)

    def _str_(self):
        return self.identifier



class keystatus(models.Model):
    identifier = models.CharField(max_length = 255, unique = True)
    label = models.CharField(max_length=100, null=False)
    order = models.IntegerField(null=False)
    is_active = models.BooleanField(null=False)

    def _str_(self):
        return self.identifier

class keyissue(models.Model):
    identifier = models.CharField(max_length=255, unique=True)
    key_id = models.ForeignKey(key, on_delete=models.CASCADE, blank=False, null=False)
    keystatus_id = models.ForeignKey(keystatus, on_delete=models.CASCADE, blank=False, null=False)
    start_date = models.DateTimeField(null=True)
    End_date = models.DateTimeField(null=True)
    ownder_id = models.CharField(max_length=6, null=True)
    person_id = models.CharField(max_length=6, null=True)
    note = models.CharField(max_length=255, blank=True, null=True)

    def _str_(self):
        return self.identifier

Key_Inventory_application/keyInventory/keys/views/building_views.py
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from ..models import building
from ..forms import buildingForm
from django.urls import reverse_lazy
from django.urls import reverse
from django.http import Http404
from django.contrib.auth.decorators import permission_required
from django.shortcuts import render, get_object_or_404, redirect
#from braces import SuperuserRequiredMixin


class buildingListView(ListView):
    model = building
    template_name = "keys/building_list.html"
    paginate_by = 20
    context_object_name = "building_list"
    allow_empty = True
    page_kwarg = 'page'
    paginate_orphans = 4

    def __init__(self, **kwargs):
        super(buildingListView, self).__init__(**kwargs)

    def dispatch(self, *args, **kwargs):
        return super(buildingListView, self).dispatch(*args, **kwargs)

    def get(self, request, *args, **kwargs):
        return super(buildingListView, self).get(request, *args, **kwargs)

    def get_queryset(self):
        return super(buildingListView, self).get_queryset()

    def get_allow_empty(self):
        return super(buildingListView, self).get_allow_empty()

    def get_context_data(self, *args, **kwargs):
        ret = super(buildingListView, self).get_context_data(*args, **kwargs)
        return ret

    def get_paginate_by(self, queryset):
        return super(buildingListView, self).get_paginate_by(queryset)

    def get_context_object_name(self, object_list):
        return super(buildingListView, self).get_context_object_name(object_list)

    def paginate_queryset(self, queryset, page_size):
        return super(buildingListView, self).paginate_queryset(queryset, page_size)

    def get_paginator(self, queryset, per_page, orphans=0, allow_empty_first_page=True):
        return super(buildingListView, self).get_paginator(queryset, per_page, orphans=0, allow_empty_first_page=True)

    def render_to_response(self, context, **response_kwargs):
        return super(buildingListView, self).render_to_response(context, **response_kwargs)

    def get_template_names(self):
        return super(buildingListView, self).get_template_names()


class buildingDetailView(DetailView):
    model = building
    template_name = "keys/building_detail.html"
    context_object_name = "building"
    slug_field = 'slug'
    slug_url_kwarg = 'slug'
    pk_url_kwarg = 'pk'

    def __init__(self, **kwargs):
        super(buildingDetailView, self).__init__(**kwargs)

    def dispatch(self, *args, **kwargs):
        return super(buildingDetailView, self).dispatch(*args, **kwargs)

    def get(self, request, *args, **kwargs):
        return super(buildingDetailView, self).get(request, *args, **kwargs)

    def get_object(self, queryset=None):
        return super(buildingDetailView, self).get_object(queryset)

    def get_queryset(self):
        return super(buildingDetailView, self).get_queryset()

    def get_slug_field(self):
        return super(buildingDetailView, self).get_slug_field()

    def get_context_data(self, **kwargs):
        ret = super(buildingDetailView, self).get_context_data(**kwargs)
        return ret

    def get_context_object_name(self, obj):
        return super(buildingDetailView, self).get_context_object_name(obj)

    def render_to_response(self, context, **response_kwargs):
        return super(buildingDetailView, self).render_to_response(context, **response_kwargs)

    def get_template_names(self):
        return super(buildingDetailView, self).get_template_names()


class buildingCreateView(CreateView):
    model = building
    form_class = buildingForm
    template_name = "keys/building_create.html"
    success_url = reverse_lazy("building_list")

    def __init__(self, **kwargs):
        super(buildingCreateView, self).__init__(**kwargs)

    def dispatch(self, request, *args, **kwargs):
        return super(buildingCreateView, self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        return super(buildingCreateView, self).get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        return super(buildingCreateView, self).post(request, *args, **kwargs)

    def get_form_class(self):
        return super(buildingCreateView, self).get_form_class()

    def get_form(self, form_class=None):
        return super(buildingCreateView, self).get_form(form_class)

    def get_form_kwargs(self, **kwargs):
        return super(buildingCreateView, self).get_form_kwargs(**kwargs)

    def get_initial(self):
        return super(buildingCreateView, self).get_initial()

    def form_invalid(self, form):
        response = super(buildingCreateView, self).form_invalid(form)
        response.status_code = 400
        return response

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.save()
        return super(buildingCreateView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        ret = super(buildingCreateView, self).get_context_data(**kwargs)
        return ret

    def render_to_response(self, context, **response_kwargs):
        return super(buildingCreateView, self).render_to_response(context, **response_kwargs)

    def get_template_names(self):
        return super(buildingCreateView, self).get_template_names()

    def get_success_url(self):
        return reverse("keys:building_detail", args=(self.object.pk,))


class buildingUpdateView(UpdateView):
    model = building
    form_class = buildingForm
    template_name = "keys/building_update.html"
    initial = {}
    slug_field = 'slug'
    slug_url_kwarg = 'slug'
    pk_url_kwarg = 'pk'
    context_object_name = "building"

    def __init__(self, **kwargs):
        super(buildingUpdateView, self).__init__(**kwargs)

    def dispatch(self, *args, **kwargs):
        return super(buildingUpdateView, self).dispatch(*args, **kwargs)

    def get(self, request, *args, **kwargs):
        return super(buildingUpdateView, self).get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        return super(buildingUpdateView, self).post(request, *args, **kwargs)

    def get_object(self, queryset=None):
        return super(buildingUpdateView, self).get_object(queryset)

    def get_queryset(self):
        return super(buildingUpdateView, self).get_queryset()

    def get_slug_field(self):
        return super(buildingUpdateView, self).get_slug_field()

    def get_form_class(self):
        return super(buildingUpdateView, self).get_form_class()

    def get_form(self, form_class=None):
        return super(buildingUpdateView, self).get_form(form_class)

    def get_form_kwargs(self, **kwargs):
        return super(buildingUpdateView, self).get_form_kwargs(**kwargs)

    def get_initial(self):
        return super(buildingUpdateView, self).get_initial()

    def form_invalid(self, form):
        response = super(buildingUpdateView, self).form_invalid(form)
        response.status_code = 400
        return response

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.save()
        return super(buildingUpdateView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        ret = super(buildingUpdateView, self).get_context_data(**kwargs)
        return ret

    def get_context_object_name(self, obj):
        return super(buildingUpdateView, self).get_context_object_name(obj)

    def render_to_response(self, context, **response_kwargs):
        return super(buildingUpdateView, self).render_to_response(context, **response_kwargs)

    def get_template_names(self):
        return super(buildingUpdateView, self).get_template_names()

    def get_success_url(self):
        return reverse("keys:building_detail", args=(self.object.pk,))


class buildingDeleteView(DeleteView):
    model = building
    template_name = "keys/building_delete.html"
    slug_field = 'slug'
    slug_url_kwarg = 'slug'
    pk_url_kwarg = 'pk'
    context_object_name = "building"

    def __init__(self, **kwargs):
        super(buildingDeleteView, self).__init__(**kwargs)

    def dispatch(self, *args, **kwargs):
        return super(buildingDeleteView, self).dispatch(*args, **kwargs)

    def get(self, request, *args, **kwargs):
        raise Http404

    def post(self, request, *args, **kwargs):
        return super(buildingDeleteView, self).post(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        return super(buildingDeleteView, self).delete(request, *args, **kwargs)

    def get_object(self, queryset=None):
        return super(buildingDeleteView, self).get_object(queryset)

    def get_queryset(self):
        return super(buildingDeleteView, self).get_queryset()

    def get_slug_field(self):
        return super(buildingDeleteView, self).get_slug_field()

    def get_context_data(self, **kwargs):
        ret = super(buildingDeleteView, self).get_context_data(**kwargs)
        return ret

    def get_context_object_name(self, obj):
        return super(buildingDeleteView, self).get_context_object_name(obj)

    def render_to_response(self, context, **response_kwargs):
        return super(buildingDeleteView, self).render_to_response(context, **response_kwargs)

    def get_template_names(self):
        return super(buildingDeleteView, self).get_template_names()

    def get_success_url(self):
        return reverse("keys:building_list")

@permission_required("admin.can_add_log_entry")
def building_deleteAll(request):
    template = "keys/building_deleteAll.html"

    prompt = {
        'warning': 'Once deleted, you will not be able to retrieve any of the records. Ensure that you are absolutely sure about you decition before you delete.'}

    if request.method == "GET":
        return render(request, template, prompt)

    building.objects.all().delete()
    response = redirect('/keys/building/')

Key_Inventory_application/keyInventory/keys/views/key_report_views.py
import csv, io
from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from ..models import building, keytype, key, keystatus, keyissue
from ..forms import buildingForm
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse


@permission_required("admin.can_add_log_entry")
def reports(request):
    template = "reports/key_reports_base.html"
    return render(request, template)

@permission_required("admin.can_add_log_entry")
def keylocation_report(request):
    template = "reports/keylocation_report.html"

    if request.method == "GET":
        return render(request, template)

    key_id = request.POST['key_id']
    print(key_id)
    # You a are going to have more than one form value like it or not.
    # You may need to handle this alittle bit later. Look into the possibility of doing the right thing.
    try:
        data_set = keyissue.objects.get(key_id=key_id)
    except keyissue.DoesNotExist:
        return HttpResponse('Exception: Data Not Found')
    print(data_set.key_id)

    current_owner = data_set.ownder_id
    date_issued = data_set.start_date
    return_date = data_set.End_date
    person_responsible = data_set.person_id
    content= {'owner' : current_owner, 'date': date_issued, 'return' : return_date, 'person' : person_responsible}
    context = {'content':content}
    return render(request,template, context)

@permission_required("admin.can_add_log_entry")
def keyuser_report(request):
    template = "reports/keyuser_report.html"

    if request.method == "GET":
        return render(request, template)

    person_id = request.POST['person_id']
    print(person_id)
    # You a are going to have more than one form value like it or not.
    try:
        data_set = keyissue.objects.all().filter(ownder_id = person_id)
        print(data_set[0])
        context = {'data':data_set,'num':1}
    except keyissue.Index:
        return HttpResponse('Exception: Data Not Found')
    return render(request, template, context)
    #Loop through every value in the context from the template and place the values inside a table and then show the table.

Key_Inventory_application/keyInventory/keys/templates/keys/building_deleteAll.html
{% extends "keys/building_base.html" %}

{% block title %}
    Delete all keytype records
{% endblock %}

{% block content %}

    {{ warning }}

    <form style="display:inline;" action={% url "keys:building_deleteAll" %} method="post" onsubmit="return confirm('Are you sure you want to delete all records?')">
        {% csrf_token %}
        <input class="btn btn-danger" type="submit" value="Delete All" />
    </form></td>
{% endblock %}

Key_Inventory_application/keyInventory/keys/templates/keys/building_update.html
{% extends "keys/building_base.html" %}

{% load crispy_forms_tags %}

{% block title %}
    Update {{ building }}
{% endblock %}

{% block content %}
    <div class = "container">
        <div class = "margin">
            <a class = "main-header" href={% url "keys:building_list" %}>Building: </a><span>Update {{ building }}</span>
        </div>

        <div class = "margin">
            <form action="" method="post">{% csrf_token %}
                {{ form | crispy }}
                 <br/>
                <input class="btn btn-primary" type="submit" value="Update" />
                <a class="btn btn-secondary"  href={% url "keys:building_detail" building.pk %}>Cancel</a>

                <form style="display:inline;" action={% url "keys:building_delete" building.pk %} method="post" onsubmit="return confirm('Are you sure you want to delete {{ building }}?')">{% csrf_token %}
                <input class="btn btn-danger" type="submit" value="Delete" />

                </form>
            </form>
            <br/>

        </div>
    </div>
{% endblock %}

Key_Inventory_application/keyInventory/keys/templates/keys/key_base.html
{% extends "base.html" %}

Key_Inventory_application/keyInventory/keys/templates/keys/key_create.html
{% extends "keys/key_base.html" %}

{% load crispy_forms_tags %}

{% block title %}
    Create key
{% endblock %}

{% block content %}
    <div class = "container">
        <div class = "margin">
            <a class = "main-header" href={% url "keys:key_list" %}>key: </a> <span>Create key</span>

        </div>

        <div class = "margin">
        <form action="" method="post">{% csrf_token %}
            {{ form | crispy }}
            <br/>
            <input class="btn btn-primary" type="submit" value="Create" />
            <a class="btn btn-secondary" href={% url "keys:key_list" %}>Cancel</a>
        </form>

        </div>
    </div>
{% endblock %}

Key_Inventory_application/keyInventory/keys/templates/keys/key_list.html
{% extends "keys/key_base.html" %}

{% block title %}
    Keys
{% endblock %}

{% block content %}
    <div class = "container margin">
        <div class = "margin">
        <a class = "main-header"> Keys </a> &emsp; &nbsp;
            {% if request.user.is_superuser %}
            <a class="report-button-primary2 bottom-margin" href={% url "keys:key_create" %}>Create new Key</a>
            {% endif %}
        </div>
        <table class="table table-striped table-responsive-md table-hover margin">
        {% for key in key_list %}
            <tr>
                <td><a href={% url "keys:key_detail" key.pk %}>{{ key.identifier }}</a></td>
                <td><a>{{ key.number }}</a></td>
                <td><a>{{ key.keytype_id }}</a></td>
                {% if request.user.is_superuser %}
                <td><a class = "update" href={% url "keys:key_update" key.pk %}>Update</a></td>
                <td><form style="display:inline;" action={% url "keys:key_delete" key.pk %} method="post" onsubmit="return confirm('Are you sure you want to delete {{ key }}?')">{% csrf_token %}<input class="list-input" type="submit" value="Delete" /></form></td>
                {% endif %}
            </tr>
        {% empty %}
            <li>No keys yet.</li>
        {% endfor %}
        </table>
    </div>
{% endblock %}

Key_Inventory_application/keyInventory/keys/templates/keys/keyissue_base.html
{% extends "base.html" %}

Key_Inventory_application/keyInventory/keys/templates/keys/keyissue_create.html
{% extends "keys/keyissue_base.html" %}

{% load crispy_forms_tags %}

{% block title %}
    Create keyissue
{% endblock %}

{% block content %}
    <div class = "container">
    <div class = "margin">
        <a class = "main-header"  href={% url "keys:keyissue_list" %}>keyissue: </a> <span>Create keyissue</span>

    </div>

        <div class = "margin">
        <form action="" method="post">{% csrf_token %}
            {{ form | crispy }}
            <br/>
            <input class="btn btn-primary" type="submit" value="Create" />
            <a class="btn btn-secondary" href={% url "keys:keyissue_list" %}>Cancel</a>
        </form>
        </div>

    </div>
{% endblock %}

Key_Inventory_application/keyInventory/keys/templates/keys/keyissue_list.html
{% extends "keys/keyissue_base.html" %}

{% block title %}
    keyissues
{% endblock %}

{% block content %}
    <div class = "container margin">
        <div class = "margin">
            <a class = "main-header">keyissues</a> &emsp; &nbsp;
            {% if request.user.is_superuser %}
            <a class="report-button-primary2 bottom-margin" href={% url "keys:keyissue_create" %}>Create new keyissue</a>
            {% endif %}
        </div>
        <table class="table table-striped table-responsive-md table-hover margin">
        {% for keyissue in keyissue_list %}
            <tr>
                <td><a href={% url "keys:keyissue_detail" keyissue.pk %}>{{ keyissue.identifier }}</a></td>
                <td><a>{{ keyissue.key_id }}</a></td>
                <td><a>{{ keyissue.keystatus_id }}</a></td>
                <td><a>{{ keyissue.start_date }}</a></td>
                <td><a>{{ keyissue.End_date }}</a></td>
                <td><a>{{ keyissue.ownder_id }}</a></td>
                <td><a>{{ keyissue.person_id }}</a></td>
                <td><a>{{ keyissue.note }}</a></td>
                {% if request.user.is_superuser %}
                <td><a class = "update" href={% url "keys:keyissue_update" keyissue.pk %}>Update</a></td>
                <td><form style="display:inline;" action={% url "keys:keyissue_delete" keyissue.pk %} method="post" onsubmit="return confirm('Are you sure you want to delete {{ keyissue }}?')">{% csrf_token %}<input class="list-input" type="submit" value="Delete" /></form></td>
                {% endif %}
            </tr>
        {% empty %}
            <li>No keyissues yet.</li>
        {% endfor %}
        </table>
    </div>
{% endblock %}

Key_Inventory_application/keyInventory/keys/templates/keys/keystatus_base.html
{% extends "base.html" %}

Key_Inventory_application/keyInventory/keys/templates/keys/keystatus_delete.html
{% extends "keys/keystatus_base.html" %}

{% block title %}
    Delete {{ keystatus }}
{% endblock %}

{% block content %}
<h1>Delete {{ keystatus }}</h1>

<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete {{ keystatus }}?</p>
    <input type="submit" value="Confirm" />
</form>

<a href={% url "keys:keystatus_detail" keystatus.pk %}>Cancel</a>

{% endblock %}

Key_Inventory_application/keyInventory/keys/templates/keys/keystatus_update.html
{% extends "keys/keystatus_base.html" %}

{% load crispy_forms_tags %}

{% block title %}
    Update {{ keystatus }}
{% endblock %}

{% block content %}
    <div class = "container">
    <div class = "margin">
        <a class = "main-header" href={% url "keys:keystatus_list" %}>keystatus: </a><span>Update {{ keystatus }}</span>
    </div>


    <div class = "margin">
        <form action="" method="post">{% csrf_token %}
            {{ form | crispy }}
            <br/>
            <input class="btn btn-primary" type="submit" value="Update" />
            <a class="btn btn-secondary"  href={% url "keys:keystatus_detail" keystatus.pk %}>Cancel</a>
            <form style="display:inline;" action={% url "keys:keystatus_delete" keystatus.pk %} method="post" onsubmit="return confirm('Are you sure you want to delete {{ keystatus }}?')">{% csrf_token %}
            <input class="btn btn-danger" type="submit" value="Delete" />
        </form>
        </form>


    </div>
    </div>
{% endblock %}

Key_Inventory_application/keyInventory/keys/templates/keys/keytype_create.html
{% extends "keys/keytype_base.html" %}

{% load crispy_forms_tags %}

{% block title %}
    Create keytype
{% endblock %}

{% block content %}
    <div class = "container">
        <div class = "margin">
            <a class = "main-header" href={% url "keys:keytype_list" %}>keytype: </a> <span>Create keytype</span>
        </div>
        <div class = "margin">
            <form action="" method="post">{% csrf_token %}
                {{ form | crispy }}
                <br/>
                <input class="btn btn-primary" type="submit" value="Create" />
                <a class="btn btn-secondary" href={% url "keys:keytype_list" %}>Cancel</a>
            </form>

        </div>
    </div>
{% endblock %}

Key_Inventory_application/keyInventory/keys/templates/keys/keytype_delete.html
{% extends "keys/keytype_base.html" %}

{% block title %}
    Delete {{ keytype }}
{% endblock %}

{% block content %}
<h1>Delete {{ keytype }}</h1>

<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete {{ keytype }}?</p>
    <input type="submit" value="Confirm" />
</form>

<a href={% url "keys
:keytype_detail" keytype.pk %}>Cancel</a>

{% endblock %}

Key_Inventory_application/keyInventory/keys/templates/keys/keytype_list.html
{% extends "keys/keytype_base.html" %}

{% block title %}
    keytype
{% endblock %}

{% block content %}
    <div class = "container margin">

        <div class = "margin">
            <a class = "main-header">keytype</a> &emsp; &nbsp;
            {% if request.user.is_superuser %}
            <a class="report-button-primary2 bottom-margin" href={% url "keys:keytype_create" %}>Create new keytype</a>
            {% endif %}
        </div>

        <table class="table table-striped table-responsive-md table-hover margin">
        {% for keytype in keytype_list %}
            <tr>
                <td><a href={% url "keys:keytype_detail" keytype.pk %}>{{ keytype.identifier }}</a></td>
                <td><a>{{ keytype.code }}</a></td>
                <td><a>{{ keytype.manu_info }}</a></td>
                <td><a>{{ keytype.description }}</a></td>
                <td><a>{{ keytype.building_id.identifier}}</a></td>
                {% if request.user.is_superuser %}
                <td><a class = "update"  href={% url "keys:keytype_update" keytype.pk %}>Update</a></td>
                <td><form style="display:inline;" action={% url "keys:keytype_delete" keytype.pk %} method="post" onsubmit="return confirm('Are you sure you want to delete {{ keytype }}?')">{% csrf_token %}<input class="list-input" type="submit" value="Delete" /></form></td>
                {% endif %}
            </tr>
        {% empty %}
            <li>No keytypes yet.</li>
        {% endfor %}
        </table>
    </div>
{% endblock %}